export const ASSET_COLORS = {
  "미국 주식": "#185fa5",
  "국내 주식": "#3b6d11",
  "장기채": "#ba7517",
  "단기채": "#ef9f27",
  "실물자산": "#639922",
  "현금": "#888780",
};

export const ASSET_CLASSES = [
  "미국 주식",
  "국내 주식",
  "장기채",
  "단기채",
  "실물자산",
  "현금",
];

export const STRATEGIES = [
  {
    id: "60_40",
    type: "fixed",
    benchmark: "balanced_60_40",
    equityBand: { min: 45, max: 70, base: 60 },
    overlays: { valuation: true, macro: true, volTarget: true, sectorMomentum: false },
    level: "초급",
    name: "미국 60/40",
    ret: "연 8%",
    mdd: "약 30%",
    rebal: "연 1회",
    irpRisk: 60,
    annualRet: { cons: 0.055, base: 0.075, opt: 0.095 },
    desc: "가장 기본적인 주식·채권 분산 전략입니다.",
    composition: [
      { cls: "미국 주식", w: 60, risk: true },
      { cls: "단기채", w: 40, risk: false },
    ],
  },
  {
    id: "permanent",
    type: "fixed",
    benchmark: "balanced_60_40",
    equityBand: { min: 35, max: 55, base: 50 },
    overlays: { valuation: true, macro: true, volTarget: true, sectorMomentum: false },
    level: "초급",
    name: "영구 포트폴리오",
    ret: "연 8%",
    mdd: "약 12.7%",
    rebal: "연 1회",
    irpRisk: 50,
    annualRet: { cons: 0.055, base: 0.075, opt: 0.09 },
    desc: "주식, 장기채, 금, 현금을 균등하게 나누는 방어형 전략입니다.",
    composition: [
      { cls: "미국 주식", w: 25, risk: true },
      { cls: "장기채", w: 25, risk: false },
      { cls: "실물자산", w: 25, risk: true },
      { cls: "현금", w: 25, risk: false },
    ],
  },
  {
    id: "permanent_global",
    type: "fixed",
    benchmark: "balanced_60_40",
    equityBand: { min: 35, max: 60, base: 50 },
    overlays: { valuation: true, macro: true, volTarget: true, sectorMomentum: false },
    level: "초급",
    name: "영구 정석",
    ret: "연 8%",
    mdd: "약 15%",
    rebal: "연 1회",
    irpRisk: 62.5,
    annualRet: { cons: 0.055, base: 0.075, opt: 0.09 },
    desc: "영구 포트폴리오를 국내외 자산으로 확장한 버전입니다.",
    composition: [
      { cls: "미국 주식", w: 12.5, risk: true },
      { cls: "국내 주식", w: 12.5, risk: true },
      { cls: "장기채", w: 25, risk: false },
      { cls: "실물자산", w: 25, risk: true },
      { cls: "현금", w: 25, risk: false },
    ],
  },
  {
    id: "allseason",
    type: "fixed",
    benchmark: "balanced_60_40",
    equityBand: { min: 35, max: 60, base: 45 },
    overlays: { valuation: true, macro: true, volTarget: true, sectorMomentum: false },
    level: "초급",
    name: "사계절 포트폴리오",
    ret: "8~10%",
    mdd: "약 13.1%",
    rebal: "연 1회",
    irpRisk: 45,
    annualRet: { cons: 0.06, base: 0.085, opt: 0.105 },
    desc: "경제 4계절을 모두 대비하는 대표적인 분산 전략입니다.",
    composition: [
      { cls: "미국 주식", w: 30, risk: true },
      { cls: "단기채", w: 15, risk: false },
      { cls: "장기채", w: 40, risk: false },
      { cls: "실물자산", w: 15, risk: true },
    ],
  },
  {
    id: "allweather",
    type: "fixed",
    benchmark: "balanced_60_40",
    equityBand: { min: 40, max: 65, base: 50 },
    overlays: { valuation: true, macro: true, volTarget: true, sectorMomentum: false },
    level: "중급",
    name: "올웨더 2.0 (심플)",
    ret: "8~10%",
    mdd: "20% 이하",
    rebal: "연 1회",
    irpRisk: 50,
    annualRet: { cons: 0.06, base: 0.085, opt: 0.105 },
    desc: "주식, 실물자산, 채권을 넓게 섞는 확장형 분산 전략입니다.",
    composition: [
      { cls: "미국 주식", w: 24, risk: true },
      { cls: "국내 주식", w: 12, risk: true },
      { cls: "실물자산", w: 14, risk: true },
      { cls: "장기채", w: 36, risk: false },
      { cls: "단기채", w: 14, risk: false },
    ],
  },
  {
    id: "gtaa5",
    type: "momentum",
    benchmark: "spy",
    equityBand: { min: 40, max: 80, base: 60 },
    overlays: { valuation: true, macro: true, volTarget: true, sectorMomentum: true },
    level: "초급",
    name: "GTAA 5 (재구성)",
    ret: "8~10%",
    mdd: "약 15%",
    rebal: "월 1회",
    irpRisk: 80,
    annualRet: { cons: 0.06, base: 0.085, opt: 0.11 },
    desc: "5개 자산의 추세를 보고 현금 대기 비중을 조절하는 전략입니다.",
    calc: "10개월 이동평균을 기준으로 상회 자산만 보유하고 나머지는 현금으로 대기합니다.",
    composition: [
      { cls: "미국 주식", w: 40, role: "dynamic", risk: true },
      { cls: "국내 주식", w: 20, role: "dynamic", risk: true },
      { cls: "장기채", w: 20, role: "dynamic", risk: false },
      { cls: "실물자산", w: 20, role: "dynamic", risk: true },
    ],
  },
  {
    id: "dual_momentum",
    type: "momentum",
    benchmark: "spy",
    equityBand: { min: 50, max: 90, base: 75 },
    overlays: { valuation: true, macro: true, volTarget: true, sectorMomentum: true },
    level: "초급",
    name: "듀얼 모멘텀",
    ret: "10~15%",
    mdd: "약 20%",
    rebal: "월 1회",
    irpRisk: 100,
    annualRet: { cons: 0.07, base: 0.1, opt: 0.13 },
    desc: "절대 모멘텀과 상대 모멘텀을 결합해 강한 자산에 집중하는 전략입니다.",
    calc: "미국주식 모멘텀이 현금보다 좋으면 미국/국내 중 강한 쪽에, 아니면 장기채로 이동합니다.",
    composition: [
      { cls: "미국 주식", role: "indicator", risk: true },
      { cls: "국내 주식", role: "relative_target", risk: true },
      { cls: "장기채", role: "defensive", risk: false },
    ],
  },
  {
    id: "laa",
    type: "momentum",
    benchmark: "spy",
    equityBand: { min: 45, max: 80, base: 50 },
    overlays: { valuation: true, macro: true, volTarget: true, sectorMomentum: false },
    level: "고급",
    name: "LAA",
    ret: "연 10%",
    mdd: "약 13%",
    rebal: "월 1회",
    irpRisk: 75,
    annualRet: { cons: 0.065, base: 0.09, opt: 0.115 },
    desc: "고정 자산 75%와 공격/방어 전환 25%를 결합한 하이브리드 전략입니다.",
    calc: "200일 이동평균과 실업률 방향을 함께 보고 공격/방어를 나눕니다.",
    composition: [
      { cls: "국내 주식", w: 25, role: "fixed", risk: true },
      { cls: "실물자산", w: 25, role: "fixed", risk: true },
      { cls: "장기채", w: 25, role: "fixed", risk: false },
      { cls: "미국 주식", w: 25, role: "attack", risk: true },
      { cls: "현금", w: 0, role: "defensive", risk: false },
    ],
  },
  {
    id: "daa",
    type: "momentum",
    benchmark: "spy",
    equityBand: { min: 40, max: 100, base: 70 },
    overlays: { valuation: true, macro: true, volTarget: true, sectorMomentum: true },
    level: "고급",
    name: "DAA",
    ret: "10~15%",
    mdd: "약 10%",
    rebal: "월 1회",
    irpRisk: 100,
    annualRet: { cons: 0.07, base: 0.1, opt: 0.13 },
    desc: "카나리아 자산으로 위험 신호를 감지해 공격/방어 비중을 전환합니다.",
    calc: "카나리아 자산의 모멘텀 점수에 따라 공격 100%, 50%, 0%를 결정합니다.",
    composition: [
      { cls: "미국 주식", role: "canary", risk: true },
      { cls: "장기채", role: "canary", risk: false },
      { cls: "미국 주식", role: "attack", w_ratio: 70, risk: true },
      { cls: "실물자산", role: "attack", w_ratio: 30, risk: true },
      { cls: "현금", role: "defensive", risk: false },
    ],
  },
];

export const ZONES = [
  { max: 15, lbl: "안정", mode: "관망", color: "#185fa5", bg: "#e6f1fb", desc: "시장 낙관이 과열된 구간입니다. 신규 매수보다 현재 비중 유지가 유리합니다." },
  { max: 25, lbl: "중립", mode: "정상 운영", color: "#3b6d11", bg: "#eaf3de", desc: "정상 변동성 구간입니다. 전략 비중 유지와 정기 적립을 이어갑니다." },
  { max: 35, lbl: "불안", mode: "방어 모드", color: "#ba7517", bg: "#faeeda", desc: "시장 불안이 커지는 구간입니다. 주식 비중 축소와 채권·현금 보강을 검토합니다." },
  { max: 999, lbl: "공황", mode: "역발상 매수", color: "#a32d2d", bg: "#fcebeb", desc: "극단적 공포 구간입니다. 분할 매수 기회지만 MDD 제한선은 반드시 확인해야 합니다." },
];

export const DEMO_PORTFOLIO = {
  strategy: "allseason",
  accountType: "연금저축",
  lastRebalDate: "2025-01-15",
  rebalPeriod: "연 1회",
  stopLoss: -20,
  mddLimit: -15,
  mdd: -6.8,
  total: 54320000,
  principalTotal: 51200000,
  holdings: [
    { etf: "TIGER 미국S&P500", code: "360750", cls: "미국 주식", target: 30, amt: 17230000, costAmt: 15800000 },
    { etf: "TIGER 미국채10년(H)", code: "305080", cls: "장기채", target: 40, amt: 22910000, costAmt: 21500000 },
    { etf: "ACE KRX금현물", code: "411060", cls: "실물자산", target: 15, amt: 7480000, costAmt: 7200000 },
    { etf: "KODEX 현금", code: "000000", cls: "현금", target: 15, amt: 6700000, costAmt: 6700000 },
  ],
  transactions: [
    { id: "demo-tx-1", tradeDate: "2025-10-15", ticker: "360750", name: "TIGER 미국S&P500", assetClass: "미국 주식", side: "buy", quantity: 45, price: 351111, fee: 3000, memo: "초기 편입" },
    { id: "demo-tx-2", tradeDate: "2025-10-15", ticker: "305080", name: "TIGER 미국채10년(H)", assetClass: "장기채", side: "buy", quantity: 52, price: 413462, fee: 3000, memo: "초기 편입" },
    { id: "demo-tx-3", tradeDate: "2025-11-20", ticker: "411060", name: "ACE KRX금현물", assetClass: "실물자산", side: "buy", quantity: 12, price: 600000, fee: 1500, memo: "분산 강화" },
    { id: "demo-tx-4", tradeDate: "2026-03-21", ticker: "360750", name: "TIGER 미국S&P500", assetClass: "미국 주식", side: "sell", quantity: 5, price: 374000, fee: 1500, memo: "차익 실현" },
  ],
  history: [
    { date: "10/15", strategy: "사계절", total: 48500000, weights: { "미국 주식": 29.8, "장기채": 54.4, "실물자산": 15.8 } },
    { date: "11/20", strategy: "사계절", total: 50200000, weights: { "미국 주식": 30.4, "장기채": 55.3, "실물자산": 14.3 } },
    { date: "오늘", strategy: "사계절", total: 54320000, weights: { "미국 주식": 31.7, "장기채": 56.0, "실물자산": 12.3 } },
  ],
  strategyOverlay: null,
};

export const RISK_DATA = {
  "미국 주식": 0.18,
  "국내 주식": 0.22,
  "장기채": 0.12,
  "단기채": 0.05,
  "실물자산": 0.18,
  "현금": 0.01,
};

