export const ASSET_COLORS = {
  미국주식: "#185fa5",
  선진국주식: "#0c447c",
  신흥국주식: "#378add",
  국내주식: "#3b6d11",
  미국장기채권: "#ba7517",
  미국중기채권: "#ef9f27",
  국내채권: "#7a8c99",
  물가연동채권: "#854f0b",
  회사채: "#d85a30",
  하이일드채권: "#a32d2d",
  신흥국채권: "#993c1d",
  글로벌채권: "#712b13",
  금: "#639922",
  원자재: "#97c459",
  부동산리츠: "#534ab7",
  현금MMF: "#888780",
};

export const ASSET_CLASSES = [
  "미국주식",
  "선진국주식",
  "신흥국주식",
  "국내주식",
  "미국장기채권",
  "미국중기채권",
  "물가연동채권",
  "회사채",
  "하이일드채권",
  "신흥국채권",
  "글로벌채권",
  "금",
  "원자재",
  "부동산리츠",
  "현금MMF",
];

export const STRATEGIES = [
  {
    id: "60_40",
    type: "fixed",
    level: "초급",
    name: "60/40 포트폴리오",
    ret: "연 8%",
    mdd: "약 30%",
    rebal: "연 1회",
    irpRisk: 60,
    annualRet: { cons: 0.055, base: 0.075, opt: 0.095 },
    desc: "가장 기본적인 주식·채권 분산 전략입니다.",
    composition: [
      { cls: "미국주식", w: 60, risk: true },
      { cls: "미국중기채권", w: 40, risk: false },
    ],
  },
  {
    id: "permanent",
    type: "fixed",
    level: "초급",
    name: "영구 포트폴리오",
    ret: "연 8%",
    mdd: "약 12.7%",
    rebal: "연 1회",
    irpRisk: 50,
    annualRet: { cons: 0.055, base: 0.075, opt: 0.09 },
    desc: "주식, 장기채, 금, 현금을 균등하게 나누는 방어형 전략입니다.",
    composition: [
      { cls: "미국주식", w: 25, risk: true },
      { cls: "미국장기채권", w: 25, risk: false },
      { cls: "금", w: 25, risk: true },
      { cls: "현금MMF", w: 25, risk: false },
    ],
  },
  {
    id: "permanent_global",
    type: "fixed",
    level: "초급",
    name: "영구 포트폴리오 글로벌",
    ret: "연 8%",
    mdd: "약 15%",
    rebal: "연 1회",
    irpRisk: 62.5,
    annualRet: { cons: 0.055, base: 0.075, opt: 0.09 },
    desc: "영구 포트폴리오를 글로벌 자산으로 확장한 버전입니다.",
    composition: [
      { cls: "미국주식", w: 12.5, risk: true },
      { cls: "선진국주식", w: 12.5, risk: true },
      { cls: "미국장기채권", w: 12.5, risk: false },
      { cls: "글로벌채권", w: 12.5, risk: false },
      { cls: "금", w: 25, risk: true },
      { cls: "현금MMF", w: 12.5, risk: false },
      { cls: "국내주식", w: 12.5, risk: true },
    ],
  },
  {
    id: "allseason",
    type: "fixed",
    level: "초급",
    name: "사계절 포트폴리오",
    ret: "8~10%",
    mdd: "약 13.1%",
    rebal: "연 1회",
    irpRisk: 45,
    annualRet: { cons: 0.06, base: 0.085, opt: 0.105 },
    desc: "경제 4계절을 모두 대비하는 대표적인 분산 전략입니다.",
    composition: [
      { cls: "미국주식", w: 30, risk: true },
      { cls: "미국중기채권", w: 15, risk: false },
      { cls: "미국장기채권", w: 40, risk: false },
      { cls: "금", w: 7.5, risk: true },
      { cls: "원자재", w: 7.5, risk: true },
    ],
  },
  {
    id: "allweather",
    type: "fixed",
    level: "중급",
    name: "올웨더 2.0",
    ret: "8~10%",
    mdd: "20% 이하",
    rebal: "연 1회",
    irpRisk: 50,
    annualRet: { cons: 0.06, base: 0.085, opt: 0.105 },
    desc: "주식, 원자재, 금, 채권을 넓게 섞는 확장형 분산 전략입니다.",
    composition: [
      { cls: "미국주식", w: 12, risk: true },
      { cls: "선진국주식", w: 12, risk: true },
      { cls: "신흥국주식", w: 12, risk: true },
      { cls: "원자재", w: 7, risk: true },
      { cls: "금", w: 7, risk: true },
      { cls: "미국장기채권", w: 18, risk: false },
      { cls: "물가연동채권", w: 18, risk: false },
      { cls: "회사채", w: 7, risk: false },
      { cls: "신흥국채권", w: 7, risk: false },
    ],
  },
  {
    id: "gtaa5",
    type: "momentum",
    level: "초급",
    name: "GTAA 5 (모멘텀)",
    ret: "8~10%",
    mdd: "약 15%",
    rebal: "월 1회",
    irpRisk: 80,
    annualRet: { cons: 0.06, base: 0.085, opt: 0.11 },
    desc: "5개 자산의 추세를 보고 현금 대기 비중을 조절하는 전략입니다.",
    calc: "10개월 이동평균을 기준으로 상회 자산만 보유하고 나머지는 현금으로 대기합니다.",
    composition: [
      { cls: "미국주식", w: 20, role: "dynamic", risk: true },
      { cls: "선진국주식", w: 20, role: "dynamic", risk: true },
      { cls: "미국중기채권", w: 20, role: "dynamic", risk: false },
      { cls: "원자재", w: 20, role: "dynamic", risk: true },
      { cls: "부동산리츠", w: 20, role: "dynamic", risk: true },
    ],
  },
  {
    id: "dual_momentum",
    type: "momentum",
    level: "초급",
    name: "듀얼 모멘텀",
    ret: "10~15%",
    mdd: "약 20%",
    rebal: "월 1회",
    irpRisk: 100,
    annualRet: { cons: 0.07, base: 0.1, opt: 0.13 },
    desc: "절대 모멘텀과 상대 모멘텀을 결합해 강한 자산에 집중하는 전략입니다.",
    calc: "미국주식 모멘텀이 현금보다 좋으면 미국/선진국 중 강한 쪽에, 아니면 장기채로 이동합니다.",
    composition: [
      { cls: "미국주식", role: "indicator", risk: true },
      { cls: "선진국주식", role: "relative_target", risk: true },
      { cls: "미국장기채권", role: "defensive", risk: false },
    ],
  },
  {
    id: "laa",
    type: "momentum",
    level: "고급",
    name: "LAA",
    ret: "연 10%",
    mdd: "약 13%",
    rebal: "월 1회",
    irpRisk: 75,
    annualRet: { cons: 0.065, base: 0.09, opt: 0.115 },
    desc: "고정 자산 75%와 공격/방어 전환 25%를 결합한 하이브리드 전략입니다.",
    calc: "200일 이동평균과 실업률 방향을 함께 보고 공격/방어를 나눕니다.",
    composition: [
      { cls: "국내주식", w: 25, role: "fixed", risk: true },
      { cls: "금", w: 25, role: "fixed", risk: true },
      { cls: "미국중기채권", w: 25, role: "fixed", risk: false },
      { cls: "미국주식", w: 25, role: "attack", risk: true },
      { cls: "현금MMF", w: 0, role: "defensive", risk: false },
    ],
  },
  {
    id: "daa",
    type: "momentum",
    level: "고급",
    name: "DAA",
    ret: "10~15%",
    mdd: "약 10%",
    rebal: "월 1회",
    irpRisk: 100,
    annualRet: { cons: 0.07, base: 0.1, opt: 0.13 },
    desc: "카나리아 자산으로 위험 신호를 감지해 공격/방어 비중을 전환합니다.",
    calc: "카나리아 자산의 모멘텀 점수에 따라 공격 100%, 50%, 0%를 결정합니다.",
    composition: [
      { cls: "신흥국주식", role: "canary", risk: true },
      { cls: "미국장기채권", role: "canary", risk: false },
      { cls: "미국주식", role: "attack", w_ratio: 70, risk: true },
      { cls: "금", role: "attack", w_ratio: 30, risk: true },
      { cls: "현금MMF", role: "defensive", risk: false },
    ],
  },
];

export const ZONES = [
  { max: 15, lbl: "안정", mode: "관망", color: "#185fa5", bg: "#e6f1fb", desc: "시장 낙관이 과열된 구간입니다. 신규 매수보다 현재 비중 유지가 유리합니다." },
  { max: 25, lbl: "중립", mode: "정상 운영", color: "#3b6d11", bg: "#eaf3de", desc: "정상 변동성 구간입니다. 전략 비중 유지와 정기 적립을 이어갑니다." },
  { max: 35, lbl: "불안", mode: "방어 모드", color: "#ba7517", bg: "#faeeda", desc: "시장 불안이 커지는 구간입니다. 주식 비중 축소와 채권·현금 보강을 검토합니다." },
  { max: 999, lbl: "공황", mode: "역발상 매수", color: "#a32d2d", bg: "#fcebeb", desc: "극단적 공포 구간입니다. 분할 매수 기회지만 MDD 제한선은 반드시 확인해야 합니다." },
];

export const DEMO_PORTFOLIO = {
  strategy: "allseason",
  accountType: "연금저축",
  lastRebalDate: "2025-01-15",
  rebalPeriod: "연 1회",
  stopLoss: -20,
  mddLimit: -15,
  mdd: -6.8,
  total: 54320000,
  principalTotal: 51200000,
  holdings: [
    { etf: "TIGER 미국S&P500", code: "360750", cls: "미국주식", target: 30, amt: 17230000, costAmt: 15800000 },
    { etf: "TIGER 미국채10년(H)", code: "305080", cls: "미국중기채권", target: 15, amt: 7480000, costAmt: 7200000 },
    { etf: "KODEX 미국채30년(H)", code: "308620", cls: "미국장기채권", target: 40, amt: 22910000, costAmt: 21500000 },
    { etf: "ACE KRX금현물", code: "411060", cls: "금", target: 7.5, amt: 3560000, costAmt: 3100000 },
    { etf: "KODEX 원자재선물(H)", code: "139290", cls: "원자재", target: 7.5, amt: 3140000, costAmt: 3600000 },
  ],
  history: [
    { date: "10/15", strategy: "사계절", total: 48500000, weights: { 미국주식: 29.8, 미국중기채권: 14.9, 미국장기채권: 39.5, 금: 8.2, 원자재: 7.6 } },
    { date: "11/20", strategy: "사계절", total: 50200000, weights: { 미국주식: 30.4, 미국중기채권: 15.1, 미국장기채권: 40.2, 금: 7.8, 원자재: 6.5 } },
    { date: "12/18", strategy: "사계절", total: 51800000, weights: { 미국주식: 31.0, 미국중기채권: 14.7, 미국장기채권: 40.8, 금: 7.4, 원자재: 6.1 } },
    { date: "01/15", strategy: "사계절", total: 53100000, weights: { 미국주식: 31.5, 미국중기채권: 14.2, 미국장기채권: 41.5, 금: 6.9, 원자재: 5.9 } },
    { date: "오늘", strategy: "사계절", total: 54320000, weights: { 미국주식: 31.7, 미국중기채권: 13.8, 미국장기채권: 42.2, 금: 6.6, 원자재: 5.7 } },
  ],
};

export const RISK_DATA = {
  미국주식: 0.18,
  선진국주식: 0.17,
  신흥국주식: 0.25,
  국내주식: 0.22,
  미국장기채권: 0.12,
  미국중기채권: 0.05,
  국내채권: 0.04,
  물가연동채권: 0.06,
  회사채: 0.08,
  하이일드채권: 0.15,
  신흥국채권: 0.14,
  글로벌채권: 0.07,
  금: 0.16,
  원자재: 0.22,
  부동산리츠: 0.18,
  현금MMF: 0.01,
};
